apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: codegen-mar17-1
  janus-idp.io/tekton: codegen-mar17-1
  backstage.io/kubernetes-id: codegen-mar17-1
  backstage.io/kubernetes-namespace: mar17-1
  app.kubernetes.io/part-of: codegen-mar17-1
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
